"""Build sp500_changes.csv: point-in-time S&P 500 membership as a baseline plus
dated changes. Not run by the app; re-run by hand to extend it.

Source: Wikipedia (CC BY-SA), raw wikitext fetched with action=raw:
  - "List of S&P 500 companies": today's constituents table;
  - "Historical components of the S&P 500": every dated change, parsed by
    wikichanges.py.
Today's membership is walked backwards through every change to the baseline,
then the changes are written forwards from it.

Why not hanshof/sp500_constituents, the MIT snapshot file: in mid-2016 it lacks
about 24 members that later left the index (CHK, DO, RIG, MNK, ECHO, YHOO, ...),
which are the names a survivorship-free universe exists to keep. It is used as
a cross-check only (README.md records the comparison).

Tickers are as Wikipedia records them: a departed company under the ticker it
left with, a renamed company that is still a member under today's ticker.

Ticker changes Wikipedia does not record as rows come from sp500_renames.csv.
On one date, renames apply first, then removals, then additions, so a ticker
handed to a new company the same day (FOX in 2019, IR in 2020) closes one
membership and opens another.

usage: python3 -I build_sp500.py LIST.wiki CHANGES.json RENAMES.csv > sp500_changes.csv
"""
import csv, json, re, sys

BASELINE = "2015-01-01"  # one year of warm-up before the first 2016 rebalance


def norm(t):
    return t.strip().replace("-", ".")


wiki = open(sys.argv[1], encoding="utf-8").read()
table = wiki[wiki.index('id="constituents"'):]
table = table[: table.index("\n|}")]
today = set()
for row in table.split("\n|-")[1:]:
    m = re.search(r"\{\{[^|}]+\|([A-Z][A-Z.\-]*)\}\}", row)  # first cell's ticker template
    if m:
        today.add(norm(m.group(1)))

changes = json.load(open(sys.argv[2]))["changes"]
by_date = {}
for c in changes:
    a, r, n = by_date.setdefault(c["date"], (set(), set(), set()))
    if c["added"]:
        a.add(norm(c["added"]))
    if c["removed"]:
        r.add(norm(c["removed"]))
for row in csv.DictReader(l for l in open(sys.argv[3]) if not l.startswith("#")):
    by_date.setdefault(row["date"], (set(), set(), set()))[2].add((norm(row["old"]), norm(row["new"])))

members = set(today)
for d in sorted(by_date, reverse=True):
    if d <= BASELINE:
        break
    a, r, n = by_date[d]
    members -= a
    members |= r
    for old, new in n:
        members.discard(new)
        members.add(old)

w = csv.writer(sys.stdout, lineterminator="\n")
print("# Point-in-time S&P 500 membership: the first row is the full membership on its date,")
print("# every later row the tickers added, removed and renamed (OLD>NEW) that day, space-separated.")
print("# On one date: renames, then removals, then additions.")
print("# Source: Wikipedia, List of S&P 500 companies + Historical components of the S&P 500 (CC BY-SA),")
print(f"# today's {len(today)} constituents walked back through {sum(1 for c in changes if c['date'] > BASELINE)} dated changes; renames: sp500_renames.csv.")
print("# Generated by build_sp500.py; do not edit rows by hand, re-fetch and re-run.")
w.writerow(["date", "added", "removed", "renamed"])
w.writerow([BASELINE, " ".join(sorted(members)), "", ""])
for d in sorted(by_date):
    if d <= BASELINE:
        continue
    a, r, n = by_date[d]
    w.writerow([d, " ".join(sorted(a)), " ".join(sorted(r)), " ".join(f"{o}>{x}" for o, x in sorted(n))])
