"""Build nq100_changes.csv from jmccarrell/n100tickers (MIT), whose yearly
n100-ticker-changes-YYYY.yaml files give the membership on January 1 plus every
dated change, with tickers as traded then (a rename is a removal and an addition
on the same day).

Each year's January 1 list is checked against the previous year's list plus its
changes; a mismatch stops the build.

usage: python3 -I build_nq100.py DIR_WITH_YAML FIRST_YEAR LAST_YEAR > nq100_changes.csv
"""
import csv, os, sys


def parse(path):
    """The files use one fixed shape; a full YAML parser is not needed for it."""
    jan1, changes, section, date, kind = [], {}, None, None, None
    for raw in open(path):
        line = raw.rstrip("\n")
        if not line.strip() or line.startswith("---") or line.startswith("year:"):
            continue
        if line.startswith("tickers_on_Jan_1:"):
            section = "jan1"
            continue
        if line.startswith("changes:"):
            section = "changes"
            continue
        s = line.strip()
        if section == "jan1" and s.startswith("- "):
            jan1.append(s[2:].strip())
        elif section == "changes":
            if line.startswith("  ") and not line.startswith("    ") and s.endswith(":"):
                date = s[:-1].strip("'\"")
                changes.setdefault(date, {"union": [], "difference": []})
            elif s in ("union:", "difference:"):
                kind = s[:-1]
            elif s.startswith("- "):
                changes[date][kind].append(s[2:].strip())
    return jan1, changes


first, last = int(sys.argv[2]), int(sys.argv[3])
years = {y: parse(os.path.join(sys.argv[1], f"{y}.yaml")) for y in range(first, last + 1)}
norm = lambda t: t.replace("-", ".")

members = {norm(t) for t in years[first][0]}
baseline = set(members)
rows = []
for y in range(first, last + 1):
    jan1 = {norm(t) for t in years[y][0]}
    if jan1 != members:
        sys.exit(f"{y}: January 1 list differs from the replay: only file {sorted(jan1 - members)}, only replay {sorted(members - jan1)}")
    for d in sorted(years[y][1]):
        add = sorted(norm(t) for t in years[y][1][d]["union"])
        rem = sorted(norm(t) for t in years[y][1][d]["difference"])
        for t in rem:
            if t not in members:
                sys.exit(f"{d}: removes {t}, not a member")
            members.discard(t)
        for t in add:
            if t in members:
                sys.exit(f"{d}: adds {t}, already a member")
            members.add(t)
        rows.append((d, add, rem))

w = csv.writer(sys.stdout, lineterminator="\n")
print("# Point-in-time Nasdaq-100 membership: the first row is the full membership on its date,")
print("# every later row the tickers added and removed that day (space-separated, as traded then).")
print(f"# Source: jmccarrell/n100tickers (MIT), n100-ticker-changes-{first}..{last}.yaml; a rename is a removal plus an addition.")
print("# Generated by build_nq100.py; do not edit rows by hand, re-fetch and re-run.")
w.writerow(["date", "added", "removed", "renamed"])
w.writerow([f"{first}-01-01", " ".join(sorted(baseline)), "", ""])
for d, a, r in rows:
    w.writerow([d, " ".join(a), " ".join(r), ""])
