"""Build history_sectors.csv: a GICS sector for every ticker the point-in-time
histories name that the source can place.

Today's S&P 500 members come from the GICS Sector column of Wikipedia's "List
of S&P 500 companies". A renamed company's earlier tickers inherit its sector
through sp500_renames.csv (FB -> META). A company that has since left the
index has no source here and is left out: the lab treats it as sector-unknown
and leaves it out of industry momentum rather than guessing.

usage: python3 -I build_sectors.py LIST.wiki sp500_renames.csv > history_sectors.csv
"""
import csv, re, sys

wiki = open(sys.argv[1], encoding="utf-8").read()
table = wiki[wiki.index('id="constituents"'):]
table = table[: table.index("\n|}")]
sector = {}
for row in table.split("\n|-")[1:]:
    cells = [c.strip() for c in re.split(r"\n\|\||\|\|", row)[1:]]
    m = re.search(r"\{\{[^|}]+\|([A-Z][A-Z.\-]*)\}\}", cells[0]) if cells else None
    if m and len(cells) > 2:
        sector[m.group(1).replace("-", ".")] = cells[2]

renames = [r for r in csv.DictReader(l for l in open(sys.argv[2]) if not l.startswith("#"))]
changed = True
while changed:  # walk chains back: CBS -> VIAC -> PARA -> PSKY
    changed = False
    for r in renames:
        if r["new"] in sector and r["old"] not in sector:
            sector[r["old"]] = sector[r["new"]]
            changed = True

w = csv.writer(sys.stdout, lineterminator="\n")
print("# GICS sector by ticker for the point-in-time histories. Today's S&P 500 members from")
print("# Wikipedia's List of S&P 500 companies (CC BY-SA); earlier tickers of renamed members through")
print("# sp500_renames.csv. Departed companies have no row. Generated by build_sectors.py.")
w.writerow(["ticker", "sector"])
for t in sorted(sector):
    w.writerow([t, sector[t]])
